# Generated by Django 6.0.6 on 2026-07-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Flagged', 'Flagged'), ('Failed', 'Failed')], max_length=20),
        ),
    ]
