# Generated by Django 6.0.6 on 2026-07-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Flagged', 'Flagged'), ('Failed', 'Failed'), ('Fraud', 'Fraud')], max_length=20),
        ),
    ]
